package ldxy.bn.entity;

public class HrDept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_dept.id
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_dept.dept_id
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    private String dept_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_dept.dept_name
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    private String dept_name;
    
    private String dept_addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_dept.dept_status
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    private Integer dept_status;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDept_id() {
		return dept_id;
	}

	public void setDept_id(String dept_id) {
		this.dept_id = dept_id;
	}

	public String getDept_name() {
		return dept_name;
	}

	public void setDept_name(String dept_name) {
		this.dept_name = dept_name;
	}

	public String getDept_addr() {
		return dept_addr;
	}

	public void setDept_addr(String dept_addr) {
		this.dept_addr = dept_addr;
	}

	public Integer getDept_status() {
		return dept_status;
	}

	public void setDept_status(Integer dept_status) {
		this.dept_status = dept_status;
	}

	@Override
	public String toString() {
		return "HrDept [id=" + id + ", dept_id=" + dept_id + ", dept_name=" + dept_name 
				+ ", dept_status=" + dept_status + "]";
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_dept.id
     *
     * @return the value of hr_dept.id
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
   
}