package ldxy.bn.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class HrEmp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_emp.id
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_emp.emp_id
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    private String emp_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_emp.emp_name
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    private String emp_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_emp.emp_pass
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    private String emp_pass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_emp.emp_sex
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    private Integer emp_sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_emp.emp_card
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    private String emp_card;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_emp.emp_birthday
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date emp_birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_emp.emp_phone
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    private String emp_phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_emp.post_id
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    private HrPost hr_post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_emp.emp_type_id
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    private HrEmpType hr_emp_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_emp.emp_salary
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    
    private Date emp_hidate;
    
    private BigDecimal emp_salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_emp.emp_status
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    private Integer emp_status;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmp_id() {
		return emp_id;
	}

	public void setEmp_id(String emp_id) {
		this.emp_id = emp_id;
	}

	public String getEmp_name() {
		return emp_name;
	}

	public void setEmp_name(String emp_name) {
		this.emp_name = emp_name;
	}

	public String getEmp_pass() {
		return emp_pass;
	}

	public void setEmp_pass(String emp_pass) {
		this.emp_pass = emp_pass;
	}

	public Integer getEmp_sex() {
		return emp_sex;
	}

	public void setEmp_sex(Integer emp_sex) {
		this.emp_sex = emp_sex;
	}

	public String getEmp_card() {
		return emp_card;
	}

	public void setEmp_card(String emp_card) {
		this.emp_card = emp_card;
	}

	public Date getEmp_birthday() {
		return emp_birthday;
	}

	public void setEmp_birthday(Date emp_birthday) {
		this.emp_birthday = emp_birthday;
	}

	public String getEmp_phone() {
		return emp_phone;
	}

	public void setEmp_phone(String emp_phone) {
		this.emp_phone = emp_phone;
	}

	public HrPost getHr_post() {
		return hr_post;
	}

	public void setHr_post(HrPost hr_post) {
		this.hr_post = hr_post;
	}

	public HrEmpType getHr_emp_type() {
		return hr_emp_type;
	}

	public void setHr_emp_type(HrEmpType hr_emp_type) {
		this.hr_emp_type = hr_emp_type;
	}

	public Date getEmp_hidate() {
		return emp_hidate;
	}

	public void setEmp_hidate(Date emp_hidate) {
		this.emp_hidate = emp_hidate;
	}

	public BigDecimal getEmp_salary() {
		return emp_salary;
	}

	public void setEmp_salary(BigDecimal emp_salary) {
		this.emp_salary = emp_salary;
	}

	public Integer getEmp_status() {
		return emp_status;
	}

	public void setEmp_status(Integer emp_status) {
		this.emp_status = emp_status;
	}

	@Override
	public String toString() {
		return "HrEmp [id=" + id + ", emp_id=" + emp_id + ", emp_name=" + emp_name + ", emp_pass=" + emp_pass
				+ ", emp_sex=" + emp_sex + ", emp_card=" + emp_card + ", emp_birthday=" + emp_birthday + ", emp_phone="
				+ emp_phone + ", hr_post=" + hr_post + ", hr_emp_type=" + hr_emp_type + ", emp_hidate=" + emp_hidate
				+ ", emp_salary=" + emp_salary + ", emp_status=" + emp_status + "]";
	}

	

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_emp.id
     *
     * @return the value of hr_emp.id
     *
     * @mbg.generated Wed Nov 28 21:15:53 CST 2018
     */
    
}